stages:
  load_data:
    cmd: python load_data.py --config ${config.config_path}
    deps:
    - ${config.config_path}
    - ${src.src_path}load_data.py
    outs:
    - ${data_load.features_path}
    - ${data_load.targets_path}
    - ${data_load.variables_path}
    - ${data_load.raw_path}
  preprocess_data:
    cmd: python preprocess.py --config ${config.config_path}
    deps:
    - ${config.config_path}
    - ${src.src_path}preprocess.py
    - ${data_load.features_path}
    - ${data_load.targets_path}
    - ${data_load.variables_path}
    - ${data_load.raw_path}
    outs:
    - ${data_split.x_train_path}
    - ${data_split.x_test_path}
    - ${data_split.y_train_path}
    - ${data_split.y_test_path}
    - ${data_preprocess.preprocessed_path}
  train_model:
    cmd: python train.py --config ${config.config_path}
    deps:
    - ${config.config_path}
    - ${src.src_path}train.py
    - ${data_split.x_train_path}
    - ${data_split.x_test_path}
    - ${data_split.y_train_path}
    - ${data_split.y_test_path}
    - ${data_preprocess.preprocessed_path}
    outs:
    - ${data_model.model_path}
  evaluate_model:
    cmd: python evaluate.py --config ${config.config_path}
    deps:
    - ${config.config_path}
    - ${src.src_path}evaluate.py
    - ${data_model.model_path}
    outs:
    - ${data_model.model_report_path}
